### ISSUE TITLE
Incomplete font

### ISSUE THREAD

**Issue by TimonPeng** [m5stack/FontCreator#1]
Use font: 黑体 (Win7 SP1)

```Arduino
#include <M5Stack.h>
#include "HT_24px.h"

void setup()
{
  M5.begin();

  M5.Lcd.setTextColor(TFT_WHITE);
  M5.Lcd.setFreeFont(&HT_24px);

  M5.Lcd.setTextDatum(TC_DATUM);

  M5.Lcd.fillScreen(0);
  M5.Lcd.setCursor(0, 30);
  M5.Lcd.printf("设置回口AgjihvtTy");
}

void loop()
{
}
```

You can see that `j`, `h` and `t` are broken, `回` and `口` have different bottom edges also.

![Display on computer](https://i.loli.net/2020/02/26/AvP6k2FfKQ7EhUR.png)

**Comment by icyqwq** [comment]
Has been fixed by font offset function.
