### ISSUE TITLE
Change data structure

### ISSUE THREAD

**Issue by TimonPeng** [m5stack/FontCreator#3]
I think users use this tool to generate GFX font from the same font every time (usually), use different fonts in the same .h file is unusual, but it's also allowed to happen too.

So I designed a new data structure to save unicode block list, use unicode as primary key to store in dict, store font info, decode text and other information in value:

```
{
    "0026":{
        "text":"&",
        "font":"some font"
    }
}
```

It's also friendly to detect conflicts and block list display:
- for detect conflicts: we can know the unicode is exists or not directly, and make an alert to asks the user whether he can keep the old one or overwrite it.
- for list display: user can see the text corresponding to unicode directly, the specified characters can be deleted too.

If you agree, I can commit a new PR.

**Comment by icyqwq** [comment]
Thanks for your work, but I have updated some function, you can submit PR again if you are still Interested in this project.

**Comment by icyqwq** [comment]
This feature has been added.

**Comment by TimonPeng** [comment]
> This feature has been added.

LGTM! Well done!
