### ISSUE TITLE
Font size couldn't be configured 

### ISSUE THREAD

**Issue by bojh** [m5stack/FontCreator#5]
because the text input field is insensitive in the windows version.
... and after installing wxPython: Fontsize could be configured - yeah!
... but the "Add" button does not open a file selection box for choosing the font (using python 3).

**Comment by bojh** [comment]
OK - understood: For different font sizes, I have to re-start the program!
And IMPORTANT: First edit the font size!
And by the way: If I change in wx_gui.py line 169 to:
`bSizer101.Add( self.fontPicker, 0, wx.ALL|wx.ALIGN_CENTER, 5 )`
... removing _VERTICAL - the python program is running :-)

**Comment by digi-thomas2003** [comment]
Hello,

since I can not install wxPython on my windows system: could you please rebuild the windows version?
So I can edit the font size.

Thank you very much!!!

Best regards
Tom

**Comment by digi-thomas2003** [comment]
Update!

I figured out that editing the font size is the **very first** step, before adding a font.
@bojh also mentioned it.

So it would be helpful, if you change the order of the steps in the description. :-)

Best regards
Tom
